# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
