#!/usr/bin/python
import sys
import os
import signal
import subprocess


param = sys.argv[1]

if param == "start":
    p = subprocess.Popen("python manage.py runserver", shell=True)
    with open("server.pid", "w") as pid_fout:
        print p.pid
        pid_fout.write(str(p.pid))

elif param == "stop":
    with open("server.pid") as pid_fin:
        pid = int(pid_fin.readline())
        print pid, signal.SIGINT
        os.kill(pid, 9)
